### PR TITLE
add RustyHermit support

### PR DESCRIPTION
**Pull request by stlankes**
RusytHermit is a library operating system, which is completely written in Rust. It provides unix-like file descriptors. Consequently, the implementation has some similarites to the Unix support.

### CODE REVIEW

**Comment by sunfishcode** [comment]
Looks great, thanks!

**Comment by sunfishcode** [comment]
This is now released in io-lifetimes 1.0.7.

**Comment by stlankes** [comment]
Thanks for the fast support!

**Comment by striezel** [comment]
Depending on how strict you view the MSRV policy, this pull requests (and the release of `io-lifetimes` 1.0.7) breaks the MSRV, which is currently Rust 1.48, because the dependency `hermit-abi` version 0.3+ requires Rust Edition 2021 (https://github.com/hermitcore/rusty-hermit/blob/98da37da30c1912f41244b6f918f300c283f117a/hermit-abi/Cargo.toml#L7). However, Rust 1.48 only supports editions up to 2018.

**Comment by sunfishcode** [comment]
As far as I can tell, it doesn't break the MSRV for existing users. The check-1.48 rule in CI passed. If there's any problem using Rust 1.48 for users of targets other than Hermit, please report it. Before this PR I assume io-lifetimes didn't work with on Hermit at all, so this PR is an improvement for Hermit.

Hermit is [Tier 3](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3), and the core Hermit ABI crate itself depends on newer Rust versions, so I think io-lifetimes is ok here.

**Comment by sunfishcode** [comment]
For what it's worth, I've now noticed that this change breaks `cargo tree` on Rust 1.48 when io-lifetimes is in the dependency tree, because `cargo tree` looks through all the dependencies of all targets. It's inconvenient, and I'll need to work around this in rustix's tests which use `cargo tree`, but I think it's ok.

**Comment by striezel** [comment]
> For what it's worth, I've now noticed that this change breaks `cargo tree` on Rust 1.48 when io-lifetimes is in the dependency tree, because `cargo tree` looks through all the dependencies of all targets.

The same happens with `cargo fetch` which also iterates over all dependencies of all targets.

It might still be considered acceptable, though, because a `cargo build` won't fail, because in that case only the dependencies for the build target are required and `hermit-abi` is skipped on non-HermitCore targets.

**Pull request merged**
