### PR TITLE
Update `windows-sys` to 0.45

### PR DESCRIPTION
**Pull request by a1phyr**

### CODE REVIEW

**Comment by sunfishcode** [comment]
Thanks for the PR! Unless there's a specific need for this, I'm expecting to wait on merging this until [the rest of the ecosystem](https://crates.io/crates/windows-sys/reverse_dependencies) starts upgrading.

**Comment by a1phyr** [comment]
I understand your concern, but I given that `io-lifetimes` is a pretty low-level crate, other (such as rustix, is-terminal, etc) will probably wait for it upgrade before doing so. If everyone waits for the ecosystem to upgrade, a deadlock will probably happen ! 

Anyway, feel free to do as you like, I don't think that anyone is in a hurry !

**Comment by sunfishcode** [comment]
Heh, that's true. Peeking around a bit, it looks like there are PRs in progress, so this'll probably proceed soon.

**Comment by sunfishcode** [comment]
Ok, things are moving. It's time to do this!

**Comment by sunfishcode** [comment]
Thanks for the PR!

**Pull request merged**
